<?php include('../includes/head.php'); ?>


<div class="onecolumn">
	<h1>Terms</h1>

<div id="wrapper">
	<div id="container">

					<p><strong>Please read these terms of use carefully.</strong> By accessing this website you agree to be bound by the terms of use below. These terms of use are subject to change. Any changes will be incorporated into the terms of use posted to this website from time to time. If you do not agree with these terms of use, please do not access this website.</p>
					<p>These Terms of Use of Start Tank Website explain a contractual agreement between you (&#8220;You&#8221;, “you”,  &#8221;your&#8221;), on one hand, and the Start Tank (“Start Tank”, “us”, “we”) on the other hand, regarding your use of this web site (&#8220;Website&#8221;)</p>
					<p>You acknowledge that Start Tank may disclose and transfer any information that you provide through this Website to (i) its affiliates, agents, service providers or information providers; (ii) to any other person or entity with your consent; or (iii) if we have a right or duty to disclose or are permitted or compelled to so disclose such information by law. You consent to the transmission, transfer or processing of such information to, or through, any country in the world, as we deem necessary or appropriate and by using and providing information through this Website you agree to such transfers. Use of this Website may be monitored, tracked and recorded. Anyone using this Website expressly consents to such monitoring, tracking and recording.</p>
					<p>Furthermore, your use of this Website signifies your agreement to our <a href="https://advertising.paypal.com/privacy-policy/">privacy statement</a>, which is incorporated herein by reference and which may also change from time to time.</p>
					<p><strong>Copyright &amp; Trademark Notices</strong></p>
					<p>The works of authorship contained in the Start Tank Website, including but not limited to all design, text, sound recordings and images, are owned, except as otherwise expressly stated, by Start Tank. Except as otherwise expressly stated herein, they may not be copied, transmitted, displayed, performed, distributed (for compensation or otherwise), licensed, altered, framed, stored for subsequent use or otherwise used in whole or in part in any manner without Start Tank’s prior written consent, except to the extent permitted by the Copyright Act of 1976 (17 U.S.C. § 107), as amended, and then, only with notices of Start Tank’s proprietary rights provided that you may download information and print out hard copies for your personal use, so long as you do not remove any copyright or other notice as may be contained in information, as downloaded.</p>
					<p><strong>Web Content and Materials</strong></p>
					<p>The information on this Website is for information purposes only. It is believed to be reliable, but Start Tank does not warrant its completeness, timeliness or accuracy. The information and materials contained in this Website &#8211; and the terms of use of the access to and use of such information and materials &#8211; are subject to change without notice. Products and services described, as well as, any fees, charges, and other requirements may differ among geographic locations. Not all products and services are offered at all locations.</p>
					<p>You agree that (i) you will not engage in any activities related to the Website that are contrary to applicable law, regulation or the terms of any agreements you may have with Start Tank; (ii) in circumstances where locations of the Website require identification, you will establish commercially reasonable security procedures and controls to limit access to your password or other identifying information to authorized individuals; (iii) you will not use any device, software, routine, file or other tool or technology, including but not limited to any viruses, trojan horses, worms, time bombs or cancelbots, intended to damage or interfere with the proper working of this Website or to surreptitiously intercept or expropriate any system, data or personal information from this Website; and (iv) you will not take any action that imposes an unreasonable or disproportionately large load on our infrastructure, including but not limited to denial of service attacks, &#8220;spam&#8221; or any other such unsolicited overload technique.</p>
					<p>Start Tank or its suppliers may discontinue or make changes in the information, products or services described herein at any time without prior notice to you and without any liability to you. Any dated information is published as of its date only, and Start Tank does not undertake any obligation or responsibility to update or amend any such information. Start Tank reserves the right to terminate any or all website offerings or transmissions without prior notice to the user. Furthermore, by offering this website and information, products or services via this website, no distribution or solicitation is made by Start Tank to any person to use the website or such information, products or services in jurisdictions where the provision of the website and such information, products or services is prohibited by law.</p>
					<p><strong>Potential Disruption of Service</strong></p>
					<p>Access to the Website may from time to time be unavailable, delayed, limited or slowed due to, among other things:</p>
					<p>Hardware failure, including among other things failures of computers (including your own computer), servers, networks, telecommunication lines and connections, and other electronic and mechanical equipment;<br />
					software failure, including among other things, bugs, errors, viruses, configuration problems, incompatibility of systems, utilities or applications, the operation of firewalls or screening programs, unreadable codes, or irregularities within particular documents or other content;<br />
					overload of system capacities;<br />
					damage caused by severe weather, earthquakes, wars, insurrection, riots, civil commotion, act of God, accident, fire, water damage, explosion, mechanical breakdown or natural disasters;<br />
					interruption (whether partial or total) of power supplies or other utility of service;<br />
					strike or other stoppage (whether partial or total) of labor;<br />
					governmental or regulatory restrictions, exchange rulings, court or tribunal orders or other human intervention; or<br />
					any other cause (whether similar or dissimilar to any of the foregoing) whatsoever beyond the control of Start Tank.</p>
					<p><strong>Links to Other Sites</strong></p>
					<p>Links to non- Start Tank websites are provided solely as pointers to information on topics that may be useful to the Websites, and Start Tank has no control over the content on such non-Start Tank websites. If you choose to link to a website not controlled by us, we make no warranties, either express or implied, concerning the content of such website, including the accuracy, completeness, reliability or suitability thereof for any particular purpose, nor do we warrant that such website or content is free from any claims of copyright, trademark or other infringement of the rights of third parties or that such site or content is devoid of viruses or other contamination. Start Tank does not guarantee the authenticity of documents on the Internet. Links to non-Start Tank websites do not imply any endorsement of or responsibility for the opinions, ideas, products, information or services offered at such sites, or any representation regarding the content at such websites.</p>
					<p><strong>LIMITATION OF LIABILITY</strong></p>
					<p>Because of the possibility of human and mechanical error as well as other factors, the website (including all information and materials contained on the website) is provided &#8220;as is&#8221; and &#8220;as available&#8221;. Start Tank and third party data providers are not providing any warranties and representations regarding the website. Start Tank and third party data providers disclaim all warranties and representations of any kind with regard to the website, including any implied warranties of merchantability, non-infringement of third party rights, freedom from viruses or other harmful code, or fitness for any particular purpose. Further, Start Tank will not be liable for any delay, difficulty in use, inaccuracy of information, computer viruses, malicious code or other defect in this website, or for the incompatibility between this website and files and the user&#8217;s browser or other site accessing program. Nor will Start Tank be liable for any other problems experienced by the user due to causes beyond Start Tank&#8217;s control. No license to the user is implied in these disclaimers. Start Tank and third party data providers do not warrant the accuracy, adequacy, or completeness of the information and materials contained on the website and expressly disclaim liability for errors or omissions in the materials and information. Furthermore, Start Tank and its affiliates will not be liable for any delay, difficulty in use, computer viruses, malicious code, or other defect in website, any incompatibility between the website and the user&#8217;s files and the user&#8217;s browser or other site accessing program, or any other problems experienced by the user due to causes beyond Start Tank and its affiliates&#8217; control. No license to the user is implied in these disclaimers. Nothing herein shall be construed as limiting or reducing Start Tank responsibilities and obligations to clients in accordance with applicable laws and regulations. Under no circumstances will Start Tank be liable for any lost profits, lost opportunity or any indirect, consequential, incidental, special, punitive, or exemplary damages arising out of any use of or inability to use the website or any portion thereof, regardless of whether Start Tank has been apprised of the likelihood of such damages occurring and regardless of the form of action, whether in contract, warranty, tort, (including negligence), strict liability, or otherwise.</p>
					<p><strong>Enforceability and Governing Law</strong></p>
					<p>Headings are for reference purposes only. The failure of Start Tank to exercise or enforce any right or provision of these Terms of Use shall not constitute a waiver of such right or provision. In the event any of the terms or provisions of these Terms of Use shall be held to be unenforceable, the remaining terms and provisions shall be unimpaired and the unenforceable term or provision shall be replaced by such enforceable term or provision as comes closest to the intention underlying the unenforceable term or provision. These Terms of Use shall be subject to any other agreements you have entered into with Start Tank. The user&#8217;s access to and use of the Start Tank Website, and the terms of this disclaimer are governed by the laws of the State of Delaware. You agree that any action brought by you, at law or in equity, arising out of or relating to these terms and use or this website shall be filed only in the state or federal courts in and for wilmington, delaware and you hereby consent and submit to the personal jurisdiction of such courts for the purposes of litigating any action brought by either of us in such courts.</p>
	</div>
</div>
</div><!-- /onecolumn -->

<div class="clr" style="margin:20px 0;"></div>


<?php include('../includes/footer.php');  ?>

